#! /bin/sh

sxhkd -c ~/.config/bspwm/sxhkdrc &
picom --config ~/.config/bspwm/picom/picom.conf --experimental-backends --animations & 
~/.config/bspwm/polybar/launch.sh &
nitrogen --restore &
dunst -config ~/.config/bspwm/dunst/dunstrc & 
xsetroot -cursor_name left_ptr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
glava --desktop &
spotifyd --no-daemon --config-path .config/spotifyd/spotifyd.conf &
plank &

# To float Alacritty when specified
declare -a floating=(alacritty-float Pcmanfm Thunar Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a GLava state=floating
bspc rule -a ranger state=floating
bspc rule -a jgmenu state=floating

bspc monitor -d 1 2 3 4 5

bspc config border_width 0
bspc config window_gap          15
bspc config bottom_padding 50

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
