#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## launch alacritty with bspwm config

if [ "$1" == "-f" ]; then
	alacritty --class 'alacritty-float,alacritty-float'
elif [ "$1" == "-r" ]; then
	alacritty --class 'alacritty-float,alacritty-float' -e $SHELL ranger
else
	alacritty --class 'alacritty-float,alacritty-float'
fi
