#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## launch alacritty with bspwm config

if [ "$1" == "-f" ]; then
	alacritty --class 'alacritty-float,alacritty-float'
elif [ "$1" == "-s" ]; then
	alacritty --class 'Fullscreen,Fullscreen' -o window.startup_mode=fullscreen window.padding.x=30 window.padding.y=30 
else
	alacritty
fi
