#! /bin/sh

sxhkd -c ~/.config/bspwm/sxhkdrc &
picom --config ~/.config/bspwm/picom/picom.conf --experimental-backends & 
~/.config/bspwm/polybar/launch.sh &
nitrogen --restore &
dunst -config ~/.config/bspwm/dunst/dunstrc & 
xsetroot -cursor_name left_ptr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d 1 2 3 4 5

bspc config border_width 0
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
